  
package:
  name: hiawatha
  version: 11.1
  description: "hiawatha"
  target-architecture:
    - all
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.16/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.16/community
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
      - https://dl-cdn.alpinelinux.org/alpine/v3.8/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.8/community

    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - scanelf
      - ssl_client
      - ca-certificates-bundle
      - openssl1.1-compat-dev      
      - musl-dev 
      - gcc 
      - libtool 
      - libc6-compat 
      - pcre-dev  
      - wget
      - tar
      - cmake 
      - make 
      - musl-dev 
      - libxml2-dev 
      - libxslt-dev 
      - util-linux 
      - php7-json 
      - php7-fpm
      - mbedtls-static

  accounts:
    groups:
      - groupname: hiawatha
        gid: 10000
    users:
      - username: hiawatha
        uid: 10000

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/hsleisink/hiawatha
      branch: v11.1
  - uses: cmake/configure
  - uses: cmake/build
  - uses: cmake/install
  - uses: strip      