  
package:
  name: hiawatha-webserver
  version: 11.1
  description: "hiawatha"
  target-architecture:
    - all
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - http://dl-cdn.alpinelinux.org/alpine/v3.8/main
      - http://dl-cdn.alpinelinux.org/alpine/v3.8/community
    packages:
      - alpine-baselayout-data
      - busybox
      - musl-dev 
      - gcc 
      - cmake 
      - make 
      - libtool 
      - libc6-compat 
      - pcre-dev  
      - wget
      - tar
      - cmake 
      - make 
      - musl-dev 
      - libxml2-dev 
      - libxslt-dev 
      - util-linux 
      - php7-json 
      - php7-fpm

  accounts:
    groups:
      - groupname: nginx
        gid: 10000
    users:
      - username: nginx
        uid: 10000

pipeline:
  - uses: fetch
    with:
      uri: https://www.hiawatha-webserver.org/files/hiawatha-11.1.tar.gz
      expected-sha256: 99c64f76927f93469f062ab76b74eb79a397ea4be12da86bf746b2bb57cf1bc5

  - uses: jwlawson/actions-setup-cmake@v1.12

  - name: 'Create build dir'
    runs: mkdir build && cd build

  - name: 'Build using cmake'
    run: cmake ..

  - name: 'Install hiawatha'
    run: make install/strip
