  
package:
  name: hiawatha
  version: 11.1
  description: "hiawatha"
  target-architecture:
    - x86_64
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - http://dl-cdn.alpinelinux.org/alpine/v3.8/main
      - http://dl-cdn.alpinelinux.org/alpine/v3.8/community
    packages:
      - alpine-baselayout-data
      - busybox
      - bash 
      - tar
      - wget
      - musl-dev 
      - gcc 
      - cmake 
      - make 
      - libtool 
      - libc6-compat 
      - pcre-dev
      - cmake 
      - make 
      - musl-dev 
      - libxml2-dev 
      - libxslt-dev 
      - util-linux 
      - php7-json 
      - php7-fpm


  accounts:
    groups:
      - groupname: hiawatha
        gid: 10000
    users:
      - username: hiawatha
        uid: 10000

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/hsleisink/hiawatha.git
      branch: master
#  - name: Run script file
#    run: |
#      chmod +x hiawatha.sh
#      ./hiawatha.sh
#    shell: bash    
  - uses: cmake/configure
  - uses: cmake/build
  - uses: cmake/install
  - uses: strip 
     
#  - name: Run the hiawatha webserver 
#    run: /usr/local/sbin/hiawatha   