  
package:
  name: hiawatha
  version: 11.1
  description: "hiawatha"
  target-architecture:
    - x86_64
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - http://dl-cdn.alpinelinux.org/alpine/v3.8/main
      - http://dl-cdn.alpinelinux.org/alpine/v3.8/community
    packages:
      - alpine-baselayout-data
      - busybox
      - musl-dev 
      - gcc 
      - cmake 
      - make 
      - libtool 
      - libc6-compat 
      - pcre-dev  
      - wget
      - tar
      - cmake 
      - make 
      - musl-dev 
      - libxml2-dev 
      - libxslt-dev 
      - util-linux 
      - php7-json 
      - php7-fpm

  accounts:
    groups:
      - groupname: hiawatha
        gid: 10000
    users:
      - username: hiawatha
        uid: 10000

pipeline:
  - uses: fetch
    with:
      uri: https://www.hiawatha-webserver.org/files/${{package.name}}-${{package.version}}.tar.gz
      expected-sha256: {{ .SHA }}
